FROM openjdk:17-slim
WORKDIR /app
# Copy the built JAR file.
# Ensure that you have run "mvn clean package" first.
COPY target/proxy-solution-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
